# Generated by Django 4.0.6 on 2023-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Delux', 'Delux')], max_length=20)),
                ('is_Booked', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='staaff_user',
            new_name='staff_user',
        ),
        migrations.DeleteModel(
            name='hotel_detail',
        ),
    ]
