# Generated by Django 4.0.6 on 2023-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_room_details_rename_staaff_user_staff_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_details',
            old_name='is_Booked',
            new_name='is_booked',
        ),
    ]
