# Generated by Django 4.0.6 on 2023-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_is_booked_room_details_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='is_booked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
