# Generated by Django 4.0.6 on 2023-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_room_details_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='checkInDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room_details',
            name='checkOutDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
