# Generated by Django 4.0.6 on 2023-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_room_details_checkindate_room_details_checkoutdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='checkInDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='checkOutDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
