# Generated by Django 4.0.6 on 2023-05-06 01:09

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_room_details_checkindate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_phone', models.PositiveIntegerField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_idproof', models.ImageField(upload_to=management.models.get_image)),
                ('room_no', models.PositiveIntegerField()),
                ('room_type', models.CharField(max_length=10)),
                ('room_status', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pending_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_phone', models.PositiveIntegerField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_idproof', models.ImageField(upload_to=management.models.get_file)),
                ('room_no', models.PositiveIntegerField()),
                ('room_type', models.CharField(max_length=10)),
                ('room_status', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
