# Generated by Django 4.0.6 on 2023-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_booking_confirmed_c_idproof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
