# Generated by Django 4.0.6 on 2023-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_payments_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
