# Generated by Django 4.0.6 on 2023-05-07 05:46

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_payments_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_phone', models.PositiveIntegerField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_idproof', models.ImageField(upload_to=management.models.get_file)),
                ('room_no', models.PositiveIntegerField()),
                ('room_type', models.CharField(max_length=10)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('room_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='pending_bookings',
        ),
    ]
