# Generated by Django 4.0.6 on 2023-05-07 09:38

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_bookings_delete_pending_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_status',
            new_name='is_booked',
        ),
        migrations.AddField(
            model_name='bookings',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_idproof',
            field=models.ImageField(blank=True, max_length=150, upload_to=management.models.get_file),
        ),
        migrations.AlterField(
            model_name='staff_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
