# Generated by Django 4.0.6 on 2023-05-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_room_status_bookings_is_booked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='c_email',
            new_name='cust_email',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='c_idproof',
            new_name='cust_idproof',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='c_name',
            new_name='cust_name',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='c_phone',
            new_name='cust_phone',
        ),
    ]
