# Generated by Django 4.0.6 on 2023-05-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_c_email_bookings_cust_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookings',
            new_name='booking',
        ),
    ]
