# Generated by Django 4.0.6 on 2023-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cust_phone',
            field=models.BigIntegerField(),
        ),
    ]
