# Generated by Django 4.0.6 on 2023-05-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_booking_cust_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking_confirmed',
            new_name='booking_history',
        ),
    ]
