# Generated by Django 4.0.6 on 2023-05-08 11:55

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rename_booking_confirmed_booking_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_history',
            old_name='c_email',
            new_name='cust_email',
        ),
        migrations.RenameField(
            model_name='booking_history',
            old_name='c_name',
            new_name='cust_name',
        ),
        migrations.RemoveField(
            model_name='booking_history',
            name='c_phone',
        ),
        migrations.RemoveField(
            model_name='booking_history',
            name='room_status',
        ),
        migrations.AddField(
            model_name='booking_history',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='cust_idproof',
            field=models.ImageField(blank=True, max_length=150, upload_to=management.models.get_file),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='cust_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='is_booked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='payment_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
