# Generated by Django 4.0.6 on 2023-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_booking_history_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='book_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
