# Generated by Django 4.0.4 on 2023-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_room_details_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
