# Generated by Django 4.0.6 on 2023-05-06 10:49

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_idproof',
            field=models.ImageField(blank=True, upload_to=hotel.models.get_image),
        ),
    ]
