# Generated by Django 4.0.6 on 2023-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_customer_c_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
