# Generated by Django 4.0.6 on 2023-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_idproof',
            field=models.ImageField(blank=True, upload_to='idproof'),
        ),
    ]
