# Generated by Django 4.0.6 on 2023-05-15 19:27

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_customer_c_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_idproof',
            field=models.ImageField(blank=True, upload_to=hotel.models.get_image),
        ),
    ]
